// Mock vehicle data that mirrors the BeForward API response structure.
// Replace this with real API calls once you have API credentials.
// Images use Wikimedia Commons public domain photos of the actual vehicles.

import { Vehicle } from './types'
import { isVehicleEligible, getEligibilityDate } from './eligibility'

const RAW_VEHICLES = [
  // ─── CURRENTLY ELIGIBLE ───────────────────────────────────────────────────
  {
    id: 'bf-001',
    make: 'Toyota',
    model: 'Supra',
    year: 1998,
    grade: 'RZ',
    mileage: 62000,
    engineDisplacement: 3000,
    engineCode: '2JZ-GTE',
    horsepower: 280,
    torque: 432,
    doors: 2,
    seats: 2,
    transmission: 'Manual' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Super White',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 28500,
    shippingEstimate: 1800,
    chassisNumber: 'JZA80-0054321',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/1994_Toyota_Supra_Sport_Roof_in_Red%2C_front_left.jpg/1280px-1994_Toyota_Supra_Sport_Roof_in_Red%2C_front_left.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Toyota_Supra_A80.jpg/1280px-Toyota_Supra_A80.jpg',
    ],
    features: ['Twin Turbo', 'HKS Exhaust', 'Recaro Seats', 'TEMS Suspension', 'Factory AC', 'Power Windows'],
    location: 'Osaka, Japan',
    stockNumber: 'BF-SUP-001',
    source: 'beforward' as const,
    description: 'Iconic 2JZ-GTE powered A80 Supra in excellent condition. Single owner, full service history. Numbers matching engine.',
  },
  {
    id: 'bf-002',
    make: 'Nissan',
    model: 'Skyline GT-R',
    year: 1999,
    grade: 'V-Spec',
    mileage: 78000,
    engineDisplacement: 2600,
    engineCode: 'RB26DETT',
    horsepower: 280,
    torque: 392,
    doors: 2,
    seats: 4,
    transmission: 'Manual' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Midnight Purple II',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 52000,
    shippingEstimate: 1800,
    chassisNumber: 'BNR34-003412',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Nissan_Skyline_R34_GT-R_N%C3%BCr_001.jpg/1280px-Nissan_Skyline_R34_GT-R_N%C3%BCr_001.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Nissan_Skyline_GT-R_%28R34%29_001.jpg/1280px-Nissan_Skyline_GT-R_%28R34%29_001.jpg',
    ],
    features: ['ATTESA E-TS Pro', 'HICAS', 'Brembo Brakes', 'Carbon Spoiler', 'Nismo Wheels', 'Boost Controller'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-GTR-002',
    source: 'beforward' as const,
    description: 'Rare V-Spec R34 GT-R in iconic Midnight Purple II. One of the most sought-after JDM icons. Full inspection report available.',
  },
  {
    id: 'bf-003',
    make: 'Honda',
    model: 'NSX',
    year: 1997,
    grade: 'Type S Zero',
    mileage: 45000,
    engineDisplacement: 3200,
    engineCode: 'C32B',
    horsepower: 280,
    torque: 304,
    doors: 2,
    seats: 2,
    transmission: 'Manual' as const,
    drivetrain: 'MR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Imola Orange Pearl',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4.5',
    price: 89000,
    shippingEstimate: 1800,
    chassisNumber: 'NA2-1009823',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/AcuraNSX-05-cropped.jpg/1280px-AcuraNSX-05-cropped.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/1997_Honda_NSX-R_%28NA2%29%2C_front_8.28.19.jpg/1280px-1997_Honda_NSX-R_%28NA2%29%2C_front_8.28.19.jpg',
    ],
    features: ['C32B VTEC Engine', 'Close-Ratio Gearbox', 'Air Conditioning', 'Power Steering', 'Titanium Shift Knob'],
    location: 'Nagoya, Japan',
    stockNumber: 'BF-NSX-003',
    source: 'beforward' as const,
    description: 'Exceptional NSX Type S Zero with factory close-ratio gearbox. Aluminum monocoque body. Ayrton Senna helped develop this car.',
  },
  {
    id: 'bf-004',
    make: 'Mazda',
    model: 'RX-7',
    year: 1999,
    grade: 'Type RS',
    mileage: 55000,
    engineDisplacement: 1300,
    engineCode: '13B-REW',
    horsepower: 265,
    torque: 314,
    doors: 2,
    seats: 2,
    transmission: 'Manual' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Vintage Red',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 34000,
    shippingEstimate: 1800,
    chassisNumber: 'FD3S-502341',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/1994_Mazda_RX-7_R2_in_Vintage_Red%2C_front_left_%28Lime_Rock%29.jpg/1280px-1994_Mazda_RX-7_R2_in_Vintage_Red%2C_front_left_%28Lime_Rock%29.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Mazda_RX-7_FD_black.jpg/1280px-Mazda_RX-7_FD_black.jpg',
    ],
    features: ['Sequential Twin Turbo', 'Torsen LSD', 'Sport Suspension', 'Sunroof', 'AC', 'Bose Audio'],
    location: 'Hiroshima, Japan',
    stockNumber: 'BF-RX7-004',
    source: 'beforward' as const,
    description: 'FD3S RX-7 Type RS in pristine condition. Rotary engine recently rebuilt with full documentation. True Japanese sports car icon.',
  },
  {
    id: 'bf-005',
    make: 'Mitsubishi',
    model: 'Lancer Evolution',
    year: 2001,
    grade: 'VII GSR',
    mileage: 88000,
    engineDisplacement: 2000,
    engineCode: '4G63T',
    horsepower: 280,
    torque: 392,
    doors: 4,
    seats: 5,
    transmission: 'Manual' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Scotia White',
    bodyType: 'Sedan',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 18500,
    shippingEstimate: 1800,
    chassisNumber: 'CT9A-0034512',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Mitsubishi_Lancer_Evolution_VII_GSR_in_Amethyst_Black%2C_front_right.jpg/1280px-Mitsubishi_Lancer_Evolution_VII_GSR_in_Amethyst_Black%2C_front_right.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mitsubishi_lancer_evolution_VII_white.jpg/1280px-Mitsubishi_lancer_evolution_VII_white.jpg',
    ],
    features: ['Active Center Differential', 'Brembo Brakes', 'MIVEC Engine', 'HKS Turbo', 'Rally Heritage'],
    location: 'Osaka, Japan',
    stockNumber: 'BF-EVO-005',
    source: 'beforward' as const,
    description: 'Evo VII GSR with ACD and AYC. World Rally heritage baked into every component. Clean chassis, strong engine.',
  },
  {
    id: 'bf-006',
    make: 'Subaru',
    model: 'Impreza WRX STI',
    year: 2000,
    grade: 'Version VI RA',
    mileage: 72000,
    engineDisplacement: 2000,
    engineCode: 'EJ207',
    horsepower: 280,
    torque: 363,
    doors: 4,
    seats: 5,
    transmission: 'Manual' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Sonic Blue Mica',
    bodyType: 'Sedan',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 22000,
    shippingEstimate: 1800,
    chassisNumber: 'GC8-0612341',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/1994-1996_Subaru_Impreza_WRX_Type_RA_STi.jpg/1280px-1994-1996_Subaru_Impreza_WRX_Type_RA_STi.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Subaru_Impreza_WRX_STi_Version_VI_RA_-_Flickr_-_The_Car_Spy_%2817%29.jpg/1280px-Subaru_Impreza_WRX_STi_Version_VI_RA_-_Flickr_-_The_Car_Spy_%2817%29.jpg',
    ],
    features: ['EJ207 Engine', 'DCCD Diff', 'STI 6-Speed', 'Bilstein Suspension', 'BBS Wheels', 'Brembo Brakes'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-STI-006',
    source: 'beforward' as const,
    description: 'GC8 Version VI RA — the legendary rally-spec model. Stripped lightweight interior, no sunroof. Original WRC-inspired machine.',
  },
  {
    id: 'bf-007',
    make: 'Toyota',
    model: 'Land Cruiser',
    year: 1998,
    grade: 'VX Limited',
    mileage: 145000,
    engineDisplacement: 4700,
    engineCode: '2UZ-FE',
    horsepower: 235,
    torque: 434,
    doors: 4,
    seats: 8,
    transmission: 'Automatic' as const,
    drivetrain: '4WD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Black',
    bodyType: 'SUV',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 16500,
    shippingEstimate: 2200,
    chassisNumber: 'UZJ100-0123456',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Toyota_Land_Cruiser_--_03-21-2012_1.JPG/1280px-Toyota_Land_Cruiser_--_03-21-2012_1.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/2000_Toyota_Land_Cruiser_%28HDJ100R%29_GXL_wagon_%282015-07-24%29_01.jpg/1280px-2000_Toyota_Land_Cruiser_%28HDJ100R%29_GXL_wagon_%282015-07-24%29_01.jpg',
    ],
    features: ['KDSS Suspension', 'Diff Lock', 'Kinetic Dynamic Suspension', 'Leather Seats', 'Navigation', 'Third Row Seating'],
    location: 'Sapporo, Japan',
    stockNumber: 'BF-LC-007',
    source: 'beforward' as const,
    description: 'FJ100 Land Cruiser VX Limited. Toyota reliability at its finest. Known to run 300k+ miles. Full off-road capability.',
  },
  {
    id: 'bf-008',
    make: 'Honda',
    model: 'Integra Type R',
    year: 2001,
    grade: 'DC5',
    mileage: 68000,
    engineDisplacement: 2000,
    engineCode: 'K20A',
    horsepower: 220,
    torque: 206,
    doors: 2,
    seats: 4,
    transmission: 'Manual' as const,
    drivetrain: 'FF' as const,
    fuelType: 'Gasoline' as const,
    color: 'Championship White',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 24000,
    shippingEstimate: 1800,
    chassisNumber: 'DC5-1034521',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/2001_Honda_Integra_Type_R_BS_O24.jpg/1280px-2001_Honda_Integra_Type_R_BS_O24.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Honda_Integra_Type_R_%28DC5%29_-_Flickr_-_Alexandre_Pr%C3%A9vot_%282%29.jpg/1280px-Honda_Integra_Type_R_%28DC5%29_-_Flickr_-_Alexandre_Pr%C3%A9vot_%282%29.jpg',
    ],
    features: ['K20A VTEC', 'LSD', 'Recaro Seats', 'Brembo Brakes', 'Sport Suspension', 'Carbon Interior Trim'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-ITR-008',
    source: 'beforward' as const,
    description: 'DC5 Integra Type R in Championship White. The last great naturally aspirated FWD sports car. Revs to 8500rpm.',
  },

  // ─── NEW ELIGIBLE VEHICLES ────────────────────────────────────────────────
  {
    id: 'bf-009',
    make: 'Nissan',
    model: 'Silvia',
    year: 1999,
    grade: 'Spec-R',
    mileage: 64000,
    engineDisplacement: 2000,
    engineCode: 'SR20DET',
    horsepower: 250,
    torque: 275,
    doors: 2,
    seats: 4,
    transmission: 'Manual' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Super Black',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 21000,
    shippingEstimate: 1800,
    chassisNumber: 'S15-000123',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Nissan_Silvia_Spec_R_b_package_%28GF-S15%29.jpg/1280px-Nissan_Silvia_Spec_R_b_package_%28GF-S15%29.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/1999_Nissan_Silvia_S15_Spec_R.jpg/1280px-1999_Nissan_Silvia_S15_Spec_R.jpg',
    ],
    features: ['SR20DET Turbo', 'Viscous LSD', 'Sports ABS', 'Bilstein Suspension', 'MOMO Steering Wheel', 'Recaro Seats'],
    location: 'Yokohama, Japan',
    stockNumber: 'BF-S15-009',
    source: 'beforward' as const,
    description: 'S15 Silvia Spec-R — the last and greatest of the Silvia line. Sharper chassis, more power, and the SR20DET that drifters worship.',
  },
  {
    id: 'bf-010',
    make: 'Honda',
    model: 'S2000',
    year: 2000,
    grade: 'AP1',
    mileage: 57000,
    engineDisplacement: 2000,
    engineCode: 'F20C',
    horsepower: 250,
    torque: 218,
    doors: 2,
    seats: 2,
    transmission: 'Manual' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Silverstone Metallic',
    bodyType: 'Convertible',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 19500,
    shippingEstimate: 1800,
    chassisNumber: 'AP1-1023456',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/HondaS2000-004.jpg/1280px-HondaS2000-004.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Year_2000_Honda_S_2000_%289934080094%29.jpg/1280px-Year_2000_Honda_S_2000_%289934080094%29.jpg',
    ],
    features: ['F20C VTEC 9000rpm', 'Close-Ratio 6-Speed', 'LSD', 'Electric Soft Top', 'Brembo Brakes', 'Sport Suspension'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-S2K-010',
    source: 'beforward' as const,
    description: 'AP1 S2000 with the legendary F20C revving to 9000rpm. No turbo needed — pure naturally aspirated perfection. Honda\'s 50th anniversary car.',
  },
  {
    id: 'bf-011',
    make: 'Toyota',
    model: 'MR2',
    year: 1994,
    grade: 'GT',
    mileage: 73000,
    engineDisplacement: 2000,
    engineCode: '3S-GTE',
    horsepower: 245,
    torque: 304,
    doors: 2,
    seats: 2,
    transmission: 'Manual' as const,
    drivetrain: 'MR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Red Mica Metallic',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 15500,
    shippingEstimate: 1800,
    chassisNumber: 'SW20-5087234',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/1993ToyotaMR2Hardtop.jpg/1280px-1993ToyotaMR2Hardtop.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/1996_Toyota_MR2_2.0_Front.jpg/1280px-1996_Toyota_MR2_2.0_Front.jpg',
    ],
    features: ['3S-GTE Turbo', 'T-bar Roof', 'Sport Suspension', 'LSD', 'Air Conditioning', 'Power Windows'],
    location: 'Nagoya, Japan',
    stockNumber: 'BF-MR2-011',
    source: 'beforward' as const,
    description: 'SW20 MR2 GT — mid-engine layout delivers Ferrari-rivaling handling. Turbocharged 3S-GTE engine. Sometimes called "the poor man\'s Ferrari" and meant as a compliment.',
  },
  {
    id: 'bf-012',
    make: 'Nissan',
    model: '300ZX',
    year: 1996,
    grade: 'Twin Turbo',
    mileage: 81000,
    engineDisplacement: 3000,
    engineCode: 'VG30DETT',
    horsepower: 280,
    torque: 392,
    doors: 2,
    seats: 2,
    transmission: 'Manual' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Burgundy',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 17500,
    shippingEstimate: 1800,
    chassisNumber: 'Z32-310042',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/1996_Nissan_300ZX_2-seater_t-top%2C_front_left_%28Lime_Rock%29.jpg/1280px-1996_Nissan_300ZX_2-seater_t-top%2C_front_left_%28Lime_Rock%29.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Nissan_300_ZX_%288490940358%29_%28cropped%29.jpg/1280px-Nissan_300_ZX_%288490940358%29_%28cropped%29.jpg',
    ],
    features: ['Twin Turbo VG30DETT', 'T-top Roof', 'Viscous LSD', 'Active Aero Spoiler', 'Bose Audio', 'HICAS Rear Steering'],
    location: 'Osaka, Japan',
    stockNumber: 'BF-Z32-012',
    source: 'beforward' as const,
    description: 'Z32 300ZX Twin Turbo — Nissan\'s grand tourer flagship. Clean-sheet design with active aerodynamics and 280ps of twin-turbocharged performance.',
  },
  {
    id: 'bf-013',
    make: 'Toyota',
    model: 'Soarer',
    year: 1993,
    grade: 'UZZ31',
    mileage: 96000,
    engineDisplacement: 4000,
    engineCode: '1UZ-FE',
    horsepower: 261,
    torque: 353,
    doors: 2,
    seats: 4,
    transmission: 'Automatic' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Crystal White Pearl',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 12000,
    shippingEstimate: 1800,
    chassisNumber: 'UZZ31-0023412',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Toyota_Soarer_30_011.jpg/1280px-Toyota_Soarer_30_011.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/1992_Toyota_Soarer_%28UZZ31%29_GT_Limited_coupe_%282015-09-13%29_01.jpg/1280px-1992_Toyota_Soarer_%28UZZ31%29_GT_Limited_coupe_%282015-09-13%29_01.jpg',
    ],
    features: ['1UZ-FE V8', 'Electronic Suspension', 'Air Suspension', 'Electro Multivision', 'Leather Interior', 'Power Moonroof'],
    location: 'Kobe, Japan',
    stockNumber: 'BF-SOA-013',
    source: 'beforward' as const,
    description: 'Z30 Soarer with silky-smooth 1UZ-FE V8. Japan\'s answer to the Mercedes SL. Advanced electronic suspension and luxurious interior still impress today.',
  },
  {
    id: 'bf-014',
    make: 'Mitsubishi',
    model: 'GTO',
    year: 1991,
    grade: 'Twin Turbo',
    mileage: 112000,
    engineDisplacement: 3000,
    engineCode: '6G72TT',
    horsepower: 280,
    torque: 427,
    doors: 2,
    seats: 2,
    transmission: 'Manual' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Pearl White',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3',
    price: 14000,
    shippingEstimate: 1800,
    chassisNumber: 'Z16A-0034521',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/1991_Mitsubishi_GTO_%2836949085656%29.jpg/1280px-1991_Mitsubishi_GTO_%2836949085656%29.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Mitsubishi_GTO_twin_turbo_%28US_3000GT%29_at_Mitsubishi_Motors_head_office%2C_Minato%2C_Tokyo.jpg/1280px-Mitsubishi_GTO_twin_turbo_%28US_3000GT%29_at_Mitsubishi_Motors_head_office%2C_Minato%2C_Tokyo.jpg',
    ],
    features: ['Twin Turbo 6G72', 'AWD', 'Active Aero', 'ECS Suspension', 'Active Exhaust', '4-Wheel Steering'],
    location: 'Hiroshima, Japan',
    stockNumber: 'BF-GTO-014',
    source: 'beforward' as const,
    description: 'Mitsubishi GTO Twin Turbo — the widebody Japanese supercar with active aerodynamics, AWD, and 4WS. Sold in the US as the 3000GT VR-4.',
  },
  {
    id: 'bf-015',
    make: 'Toyota',
    model: 'Chaser',
    year: 1997,
    grade: 'Tourer V',
    mileage: 91000,
    engineDisplacement: 2500,
    engineCode: '1JZ-GTE',
    horsepower: 280,
    torque: 363,
    doors: 4,
    seats: 5,
    transmission: 'Automatic' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Graphite Gray Mica',
    bodyType: 'Sedan',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 13500,
    shippingEstimate: 1800,
    chassisNumber: 'JZX100-0041293',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/1996-1998_Toyota_Chaser.jpg/1280px-1996-1998_Toyota_Chaser.jpg',
    ],
    features: ['1JZ-GTE Twin Cam Turbo', 'Super TECS Auto', 'Sport Suspension', 'Leather Seats', 'Navigation', 'LSD'],
    location: 'Nagoya, Japan',
    stockNumber: 'BF-CHA-015',
    source: 'beforward' as const,
    description: 'JZX100 Chaser Tourer V — the drift community\'s sleeper. Factory 280ps 1JZ-GTE under the hood with subtle executive styling.',
  },
  {
    id: 'bf-016',
    make: 'Honda',
    model: 'Prelude',
    year: 1998,
    grade: 'Type S',
    mileage: 66000,
    engineDisplacement: 2200,
    engineCode: 'H22A',
    horsepower: 220,
    torque: 220,
    doors: 2,
    seats: 4,
    transmission: 'Manual' as const,
    drivetrain: 'FF' as const,
    fuelType: 'Gasoline' as const,
    color: 'Milano Red',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 9500,
    shippingEstimate: 1800,
    chassisNumber: 'BB6-1023981',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/1998_Honda_Prelude_VTi_Automatic_2.2_Front.jpg/1280px-1998_Honda_Prelude_VTi_Automatic_2.2_Front.jpg',
    ],
    features: ['H22A VTEC', 'ATTS (Active Torque Transfer)', 'Sport Suspension', '4-Wheel Steering', 'Moonroof', 'AC'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-PRE-016',
    source: 'beforward' as const,
    description: 'Fifth-gen BB6 Prelude Type S with Honda\'s ATTS torque-vectoring system. One of the most technically advanced FWD coupes ever built.',
  },
  {
    id: 'bf-017',
    make: 'Toyota',
    model: 'Aristo',
    year: 1993,
    grade: 'V300',
    mileage: 104000,
    engineDisplacement: 3000,
    engineCode: '2JZ-GTE',
    horsepower: 280,
    torque: 432,
    doors: 4,
    seats: 5,
    transmission: 'Automatic' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Black Pearl Crystal',
    bodyType: 'Sedan',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 11000,
    shippingEstimate: 1800,
    chassisNumber: 'JZS147-0012891',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/1st_generation_Toyota_Aristo.jpg/1280px-1st_generation_Toyota_Aristo.jpg',
    ],
    features: ['2JZ-GTE Twin Turbo', 'Air Suspension', 'Leather Interior', 'Navigation', 'Sunroof', 'JBL Audio'],
    location: 'Osaka, Japan',
    stockNumber: 'BF-ARI-017',
    source: 'beforward' as const,
    description: 'JZS147 Aristo V300 — the executive sleeper with a 2JZ-GTE under the hood. Sold in the US as the Lexus GS300 but with the twin-turbo engine Japan kept for itself.',
  },
  {
    id: 'bf-018',
    make: 'Nissan',
    model: 'Stagea',
    year: 1997,
    grade: 'RS Four',
    mileage: 98000,
    engineDisplacement: 2500,
    engineCode: 'RB25DET',
    horsepower: 260,
    torque: 353,
    doors: 4,
    seats: 5,
    transmission: 'Automatic' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Dark Blue',
    bodyType: 'Wagon',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 12500,
    shippingEstimate: 1800,
    chassisNumber: 'WC34-034512',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/1996_Nissan_Stagea_C34.jpg/1280px-1996_Nissan_Stagea_C34.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/1998_Nissan_Stagea_Autech_Version_260RS_%28WGNC34%29%2C_front_8.3.19.jpg/1280px-1998_Nissan_Stagea_Autech_Version_260RS_%28WGNC34%29%2C_front_8.3.19.jpg',
    ],
    features: ['RB25DET Turbo', 'ATTESA AWD', 'HICAS Rear Steering', 'Bilstein Suspension', 'Auto LSD', 'Bose Audio'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-STA-018',
    source: 'beforward' as const,
    description: 'WC34 Stagea RS Four — Skyline GT-R drivetrain in a practical wagon body. The Autech version even shared the R33\'s front end. Practicality meets performance.',
  },

  // ─── COMING SOON ─────────────────────────────────────────────────────────
  {
    id: 'cs-001',
    make: 'Nissan',
    model: 'GT-R',
    year: 2009,
    grade: 'Premium',
    mileage: 42000,
    engineDisplacement: 3800,
    engineCode: 'VR38DETT',
    horsepower: 485,
    torque: 588,
    doors: 2,
    seats: 4,
    transmission: 'Automatic' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Ultimate Opal',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 68000,
    shippingEstimate: 1800,
    chassisNumber: 'R35-012345',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Nissan_GT-R_R35_-_Hagerty_-_004.jpg/1280px-Nissan_GT-R_R35_-_Hagerty_-_004.jpg',
    ],
    features: ['Twin Turbo VR38DETT', 'Dual-Clutch Transmission', 'Brembo Brakes', 'Bilstein Suspension'],
    location: 'Tokyo, Japan',
    stockNumber: 'CS-GTR-001',
    source: 'beforward' as const,
    description: 'R35 GT-R — the supercar killer. 0-60 in 2.7 seconds. Godzilla awaits.',
  },
  {
    id: 'cs-002',
    make: 'Toyota',
    model: 'GR Supra',
    year: 2020,
    grade: 'SZ-R',
    mileage: 18000,
    engineDisplacement: 2000,
    engineCode: 'B58',
    horsepower: 258,
    torque: 400,
    doors: 2,
    seats: 2,
    transmission: 'Automatic' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Horizon Blue',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4.5',
    price: 42000,
    shippingEstimate: 1800,
    chassisNumber: 'DB42-0002341',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/2020_Toyota_GR_Supra_3.0%2C_front_8.22.19.jpg/1280px-2020_Toyota_GR_Supra_3.0%2C_front_8.22.19.jpg',
    ],
    features: ['B58 Turbo Engine', 'Active Differential', 'Adaptive Suspension', 'JBL Audio', 'Head-Up Display'],
    location: 'Osaka, Japan',
    stockNumber: 'CS-GRS-002',
    source: 'beforward' as const,
    description: 'A90 GR Supra SZ-R. BMW-powered revival of the legendary nameplate. Not yet eligible but coming soon.',
  },
  {
    id: 'cs-003',
    make: 'Honda',
    model: 'Civic Type R',
    year: 2017,
    grade: 'FK8',
    mileage: 28000,
    engineDisplacement: 2000,
    engineCode: 'K20C1',
    horsepower: 320,
    torque: 400,
    doors: 4,
    seats: 5,
    transmission: 'Manual' as const,
    drivetrain: 'FF' as const,
    fuelType: 'Gasoline' as const,
    color: 'Championship White',
    bodyType: 'Hatchback',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 32000,
    shippingEstimate: 1800,
    chassisNumber: 'FK8-0198234',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/2017_Honda_Civic_Type_R_%28FK8%29%2C_front_8.3.19.jpg/1280px-2017_Honda_Civic_Type_R_%28FK8%29%2C_front_8.3.19.jpg',
    ],
    features: ['K20C1 Turbo', 'LSD', 'Brembo Brakes', 'Adaptive Dampers', '+R Mode'],
    location: 'Tokyo, Japan',
    stockNumber: 'CS-CTR-003',
    source: 'beforward' as const,
    description: 'FK8 Civic Type R — Nurburgring FWD lap record holder at time of release.',
  },
]

export function buildVehicleList(): Vehicle[] {
  return RAW_VEHICLES.map((v) => {
    const eligible = isVehicleEligible(v.year)
    return {
      ...v,
      totalLandedCost: v.price + v.shippingEstimate + Math.round(v.price * 0.025),
      isEligible: eligible,
      eligibilityDate: getEligibilityDate(v.year),
    }
  })
}

export const MOCK_VEHICLES: Vehicle[] = buildVehicleList()
