// Mock vehicle data that mirrors the BeForward API response structure.
// Replace this with real API calls once you have API credentials.
// Images use Wikimedia Commons public domain photos of the actual vehicles.

import { Vehicle } from './types'
import { isVehicleEligible, getEligibilityDate } from './eligibility'

const RAW_VEHICLES = [
  {
    id: 'bf-001',
    make: 'Toyota',
    model: 'Supra',
    year: 1998,
    grade: 'RZ',
    mileage: 62000,
    engineDisplacement: 3000,
    transmission: 'Manual' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Super White',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 28500,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Toyota_Supra_MKIV_front_angle.jpg/1280px-Toyota_Supra_MKIV_front_angle.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/1993-1998_Toyota_Supra_RZ_--_09-28-2011.jpg/1280px-1993-1998_Toyota_Supra_RZ_--_09-28-2011.jpg',
    ],
    features: ['Turbo', 'HKS Exhaust', 'Recaro Seats', 'TEMS Suspension', 'Factory AC', 'Power Windows'],
    location: 'Osaka, Japan',
    stockNumber: 'BF-SUP-001',
    source: 'beforward' as const,
    description: 'Iconic 2JZ-GTE powered A80 Supra in excellent condition. Single owner, full service history. Numbers matching engine.',
  },
  {
    id: 'bf-002',
    make: 'Nissan',
    model: 'Skyline GT-R',
    year: 1999,
    grade: 'V-Spec',
    mileage: 78000,
    engineDisplacement: 2600,
    transmission: 'Manual' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Midnight Purple II',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 52000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/1999_Nissan_Skyline_R34_GT-R_V-spec%2C_front_8.3.19.jpg/1280px-1999_Nissan_Skyline_R34_GT-R_V-spec%2C_front_8.3.19.jpg',
    ],
    features: ['ATTESA E-TS Pro', 'HICAS', 'Brembo Brakes', 'Carbon Spoiler', 'Nismo Wheels', 'Boost Controller'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-GTR-002',
    source: 'beforward' as const,
    description: 'Rare V-Spec R34 GT-R in iconic Midnight Purple II. One of the most sought-after JDM icons. Full inspection report available.',
  },
  {
    id: 'bf-003',
    make: 'Honda',
    model: 'NSX',
    year: 1997,
    grade: 'Type S Zero',
    mileage: 45000,
    engineDisplacement: 3200,
    transmission: 'Manual' as const,
    drivetrain: 'MR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Imola Orange Pearl',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4.5',
    price: 89000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Honda_NSX_NA1_orange_-_Goodwood_Festival_of_Speed_2014_%2814399731087%29.jpg/1280px-Honda_NSX_NA1_orange_-_Goodwood_Festival_of_Speed_2014_%2814399731087%29.jpg',
    ],
    features: ['C32B VTEC Engine', 'Close-Ratio Gearbox', 'Air Conditioning', 'Power Steering', 'Titanium Shift Knob'],
    location: 'Nagoya, Japan',
    stockNumber: 'BF-NSX-003',
    source: 'beforward' as const,
    description: 'Exceptional NSX Type S Zero with factory close-ratio gearbox. Aluminum monocoque body. Ayrton Senna helped develop this car.',
  },
  {
    id: 'bf-004',
    make: 'Mazda',
    model: 'RX-7',
    year: 1999,
    grade: 'Type RS',
    mileage: 55000,
    engineDisplacement: 1300,
    transmission: 'Manual' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Vintage Red',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 34000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Mazda_RX-7_FD_-_front_%28cropped%29.jpg/1280px-Mazda_RX-7_FD_-_front_%28cropped%29.jpg',
    ],
    features: ['Sequential Twin Turbo', 'Torsen LSD', 'Sport Suspension', 'Sunroof', 'AC', 'Bose Audio'],
    location: 'Hiroshima, Japan',
    stockNumber: 'BF-RX7-004',
    source: 'beforward' as const,
    description: 'FD3S RX-7 Type RS in pristine condition. Rotary engine recently rebuilt with full documentation. True Japanese sports car icon.',
  },
  {
    id: 'bf-005',
    make: 'Mitsubishi',
    model: 'Lancer Evolution',
    year: 2001,
    grade: 'VII GSR',
    mileage: 88000,
    engineDisplacement: 2000,
    transmission: 'Manual' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Scotia White',
    bodyType: 'Sedan',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 18500,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Mitsubishi_Lancer_Evolution_VII_001.jpg/1280px-Mitsubishi_Lancer_Evolution_VII_001.jpg',
    ],
    features: ['Active Center Differential', 'Brembo Brakes', 'MIVEC Engine', 'HKS Turbo', 'Rally Heritage'],
    location: 'Osaka, Japan',
    stockNumber: 'BF-EVO-005',
    source: 'beforward' as const,
    description: 'Evo VII GSR with ACD and AYC. World Rally heritage baked into every component. Clean chassis, strong engine.',
  },
  {
    id: 'bf-006',
    make: 'Subaru',
    model: 'Impreza WRX STI',
    year: 2000,
    grade: 'Version VI RA',
    mileage: 72000,
    engineDisplacement: 2000,
    transmission: 'Manual' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Sonic Blue Mica',
    bodyType: 'Sedan',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 22000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Subaru_Impreza_WRX_STi_Version_VI_RA_-_GC8_%281999-2000%29.jpg/1280px-Subaru_Impreza_WRX_STi_Version_VI_RA_-_GC8_%281999-2000%29.jpg',
    ],
    features: ['EJ207 Engine', 'DCCD Diff', 'STI 6-Speed', 'Bilstein Suspension', 'BBS Wheels', 'Brembo Brakes'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-STI-006',
    source: 'beforward' as const,
    description: 'GC8 Version VI RA — the legendary rally-spec model. Stripped lightweight interior, no sunroof. Original WRC-inspired machine.',
  },
  {
    id: 'bf-007',
    make: 'Toyota',
    model: 'Land Cruiser',
    year: 1998,
    grade: 'VX Limited',
    mileage: 145000,
    engineDisplacement: 4700,
    transmission: 'Automatic' as const,
    drivetrain: '4WD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Black',
    bodyType: 'SUV',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '3.5',
    price: 16500,
    shippingEstimate: 2200,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Toyota_Land_Cruiser_100_VX_Limited_G-Selection_%28J100%2C_first_generation%29%2C_front_8.4.19.jpg/1280px-Toyota_Land_Cruiser_100_VX_Limited_G-Selection_%28J100%2C_first_generation%29%2C_front_8.4.19.jpg',
    ],
    features: ['KDSS Suspension', 'Diff Lock', 'Kinetic Dynamic Suspension', 'Leather Seats', 'Navigation', 'Third Row Seating'],
    location: 'Sapporo, Japan',
    stockNumber: 'BF-LC-007',
    source: 'beforward' as const,
    description: 'FJ100 Land Cruiser VX Limited. Toyota reliability at its finest. Known to run 300k+ miles. Full off-road capability.',
  },
  {
    id: 'bf-008',
    make: 'Honda',
    model: 'Integra Type R',
    year: 2001,
    grade: 'DC5',
    mileage: 68000,
    engineDisplacement: 2000,
    transmission: 'Manual' as const,
    drivetrain: 'FF' as const,
    fuelType: 'Gasoline' as const,
    color: 'Championship White',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 24000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/2002_Honda_Integra_Type_R_%28DC5%29%2C_front_8.3.19.jpg/1280px-2002_Honda_Integra_Type_R_%28DC5%29%2C_front_8.3.19.jpg',
    ],
    features: ['K20A VTEC', 'LSD', 'Recaro Seats', 'Brembo Brakes', 'Sport Suspension', 'Carbon Interior Trim'],
    location: 'Tokyo, Japan',
    stockNumber: 'BF-ITR-008',
    source: 'beforward' as const,
    description: 'DC5 Integra Type R in Championship White. The last great naturally aspirated FWD sports car. Revs to 8500rpm.',
  },
  // Coming soon vehicles (post 2001)
  {
    id: 'cs-001',
    make: 'Nissan',
    model: 'GT-R',
    year: 2009,
    grade: 'Premium',
    mileage: 42000,
    engineDisplacement: 3800,
    transmission: 'Automatic' as const,
    drivetrain: 'AWD' as const,
    fuelType: 'Gasoline' as const,
    color: 'Ultimate Opal',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 68000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Nissan_GT-R_R35_-_Hagerty_-_004.jpg/1280px-Nissan_GT-R_R35_-_Hagerty_-_004.jpg',
    ],
    features: ['Twin Turbo VR38DETT', 'Dual-Clutch Transmission', 'Brembo Brakes', 'Bilstein Suspension'],
    location: 'Tokyo, Japan',
    stockNumber: 'CS-GTR-001',
    source: 'beforward' as const,
    description: 'R35 GT-R — the supercar killer. 0-60 in 2.7 seconds. Godzilla awaits.',
  },
  {
    id: 'cs-002',
    make: 'Toyota',
    model: 'GR Supra',
    year: 2020,
    grade: 'SZ-R',
    mileage: 18000,
    engineDisplacement: 2000,
    transmission: 'Automatic' as const,
    drivetrain: 'FR' as const,
    fuelType: 'Gasoline' as const,
    color: 'Horizon Blue',
    bodyType: 'Coupe',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4.5',
    price: 42000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/2020_Toyota_GR_Supra_3.0%2C_front_8.22.19.jpg/1280px-2020_Toyota_GR_Supra_3.0%2C_front_8.22.19.jpg',
    ],
    features: ['B58 Turbo Engine', 'Active Differential', 'Adaptive Suspension', 'JBL Audio', 'Head-Up Display'],
    location: 'Osaka, Japan',
    stockNumber: 'CS-GRS-002',
    source: 'beforward' as const,
    description: 'A90 GR Supra SZ-R. BMW-powered revival of the legendary nameplate. Not yet eligible but coming soon.',
  },
  {
    id: 'cs-003',
    make: 'Honda',
    model: 'Civic Type R',
    year: 2017,
    grade: 'FK8',
    mileage: 28000,
    engineDisplacement: 2000,
    transmission: 'Manual' as const,
    drivetrain: 'FF' as const,
    fuelType: 'Gasoline' as const,
    color: 'Championship White',
    bodyType: 'Hatchback',
    steeringType: 'Right Hand Drive' as const,
    auctionGrade: '4',
    price: 32000,
    shippingEstimate: 1800,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/2017_Honda_Civic_Type_R_%28FK8%29%2C_front_8.3.19.jpg/1280px-2017_Honda_Civic_Type_R_%28FK8%29%2C_front_8.3.19.jpg',
    ],
    features: ['K20C1 Turbo', 'LSD', 'Brembo Brakes', 'Adaptive Dampers', '+R Mode'],
    location: 'Tokyo, Japan',
    stockNumber: 'CS-CTR-003',
    source: 'beforward' as const,
    description: 'FK8 Civic Type R — Nurburgring FWD lap record holder at time of release.',
  },
]

export function buildVehicleList(): Vehicle[] {
  return RAW_VEHICLES.map((v) => {
    const eligible = isVehicleEligible(v.year)
    return {
      ...v,
      totalLandedCost: v.price + v.shippingEstimate + Math.round(v.price * 0.025),
      isEligible: eligible,
      eligibilityDate: getEligibilityDate(v.year),
    }
  })
}

export const MOCK_VEHICLES: Vehicle[] = buildVehicleList()
